# Generated by Django 3.2.5 on 2021-09-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000)),
                ('details', models.CharField(blank=True, default='', max_length=1000)),
                ('image', models.CharField(blank=True, default='', max_length=10485759)),
                ('video', models.CharField(blank=True, default='', max_length=1000)),
                ('date', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='ads',
            field=models.ManyToManyField(blank=True, related_name='cars', to='car.Ad'),
        ),
    ]
