# Generated by Django 3.2.5 on 2021-09-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20210910_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='details',
        ),
    ]
