# Generated by Django 3.2.5 on 2021-09-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_ad_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='videoID',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='videoID',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
