# Generated by Django 3.2.5 on 2021-09-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20210911_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='payementWay',
            new_name='paymentWay',
        ),
    ]
