# Generated by Django 3.2.5 on 2021-09-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favList',
            field=models.ManyToManyField(blank=True, related_name='users', to='car.Car'),
        ),
    ]
