# Generated by Django 3.2.5 on 2021-09-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_car_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='flaws',
            field=models.TextField(blank=True, default='', max_length=10485759),
        ),
    ]
