# Generated by Django 3.2.5 on 2021-09-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_car_totalev'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='sold',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=10485759),
        ),
    ]
