# Generated by Django 3.2.5 on 2021-09-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_auto_20210922_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='username',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
