# Generated by Django 3.2.5 on 2021-09-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0019_car_motorst'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
