# Generated by Django 3.2.5 on 2021-09-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0020_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='car',
            name='sort',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
