# Generated by Django 3.2.5 on 2021-09-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0021_auto_20210929_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelText', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortText', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='sort',
        ),
        migrations.AddField(
            model_name='car',
            name='modelList',
            field=models.ManyToManyField(blank=True, related_name='modelItems', to='car.CarModel'),
        ),
        migrations.AddField(
            model_name='car',
            name='sortList',
            field=models.ManyToManyField(blank=True, related_name='sortItems', to='car.Sort'),
        ),
    ]
