# Generated by Django 3.2.5 on 2021-09-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0022_auto_20210929_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='modelList',
        ),
        migrations.RemoveField(
            model_name='car',
            name='sortList',
        ),
        migrations.AddField(
            model_name='car',
            name='modelText',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='car',
            name='sortText',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
