# Generated by Django 3.2.5 on 2021-09-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0023_auto_20210930_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='modelText',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='car',
            name='sortText',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='modelText',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='sort',
            name='sortText',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
