# Generated by Django 3.2.5 on 2021-09-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0025_favcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='favcar',
            name='likesCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
