# Generated by Django 3.2.5 on 2021-09-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0026_favcar_likescount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favcar',
            name='commentList',
        ),
        migrations.AddField(
            model_name='favcar',
            name='userID',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
