# Generated by Django 3.2.5 on 2021-09-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0028_favcar_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='favcar',
            name='userPic',
            field=models.CharField(blank=True, default='', max_length=10485759),
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.CharField(blank=True, default='', max_length=10485759),
        ),
    ]
