# Generated by Django 3.2.5 on 2021-10-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0030_favcar_commentlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewsCount', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
