# Generated by Django 3.2.5 on 2021-10-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0032_user_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='carID',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
